modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "Custom"

[[mods]]
modId = "lilis_lucky_lures"
version = "${version}"
displayName = "[Let's Do] Lilis Lucky Lures"
authors = "Satisfy, MissLilitu"
description = '''
Let's go fishing! We pack our Gear: A Fishing Fod, Fishing Hat, Dynamite... Dynamite? Lili's Lucky Lures adds extra ways to catch Fish, complete with Fish & Rubble Pools and a modest Collection of Decorative Blocks.
'''
logoFile = "pack.png"

[[dependencies.lilis_lucky_lures]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilis_lucky_lures]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilis_lucky_lures]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"