modLoader = "javafml"
loaderVersion="[4,)"
source = "https://github.com/Let-s-Do-Collection/LilisLuckyLures"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "All Rights Reserved"

credits = "CR-055"
[[mixins]]
config = "lilis_lucky_lures-common.mixins.json, lilis_lucky_lures.mixins.json"

[[mods]]
modId = "lilis_lucky_lures"

version="${mod_version}"
displayName = "[Let's Do] Lilis Lucky Lures"

authors = "Satisfy, MissLilitu"
description = '''
Let's go fishing! We pack our Gear: A Fishing Fod, Fishing Hat, Dynamite... Dynamite? Lili's Lucky Lures adds extra ways to catch Fish, complete with Fish & Rubble Pools and a modest Collection of Decorative Blocks.
'''
logoFile = "pack.png"

[[dependencies.lilis_lucky_lures]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilis_lucky_lures]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lilis_lucky_lures]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.lilis_lucky_lures]]
modId = "doapi"
type = "required"
versionRange = "[1.2.0,)"
ordering = "NONE"
side = "BOTH"
